services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/challenge_tech_development
      MONGODB_URI_TEST: mongodb://mongo:27017/challenge_tech_test
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - .:/rails
    command: ./bin/rails server -b 0.0.0.0

  sidekiq:
    build: .
    environment:
      MONGODB_URI: mongodb://mongo:27017/challenge_tech_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - .:/rails
    command: bundle exec sidekiq
    restart: on-failure

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongo_data:
